List countryCodes = [
  {
    "name": "United Arab Emirates",
    "dial_code": "+971",
    "code": "AE",
    "emoji": "🇦🇪",
    "phone_length": 9,
  },
  {
    "name": "India",
    "dial_code": "+91",
    "code": "IN",
    "emoji": "🇮🇳",
    "phone_length": 10,
  },
  {
    "name": "Afghanistan",
    "dial_code": "+93",
    "code": "AF",
    "emoji": "🇦🇫",
    "phone_length": 9,
  },
  {
    "name": "Aland Islands",
    "dial_code": "+358",
    "code": "AX",
    "emoji": "🇦🇽",
    "phone_length": 10,
  },
  {
    "name": "Albania",
    "dial_code": "+355",
    "code": "AL",
    "emoji": "🇦🇱",
    "phone_length": 9,
  },
  {
    "name": "Algeria",
    "dial_code": "+213",
    "code": "DZ",
    "emoji": "🇩🇿",
    "phone_length": 9,
  },
  {
    "name": "American Samoa",
    "dial_code": "+1684",
    "code": "AS",
    "emoji": "🇦🇸",
    "phone_length": 10,
  },
  {
    "name": "Andorra",
    "dial_code": "+376",
    "code": "AD",
    "emoji": "🇦🇩",
    "phone_length": 6,
  },
  {
    "name": "Angola",
    "dial_code": "+244",
    "code": "AO",
    "emoji": "🇦🇴",
    "phone_length": 9,
  },
  {
    "name": "Anguilla",
    "dial_code": "+1264",
    "code": "AI",
    "emoji": "🇦🇮",
    "phone_length": 10,
  },
  {
    "name": "Antarctica",
    "dial_code": "+672",
    "code": "AQ",
    "emoji": "🇦🇶",
    "phone_length": 6,
  },
  {
    "name": "Antigua and Barbuda",
    "dial_code": "+1268",
    "code": "AG",
    "emoji": "🇦🇬",
    "phone_length": 10,
  },
  {
    "name": "Argentina",
    "dial_code": "+54",
    "code": "AR",
    "emoji": "🇦🇷",
    "phone_length": 8,
  },
  {
    "name": "Armenia",
    "dial_code": "+374",
    "code": "AM",
    "emoji": "🇦🇲",
    "phone_length": 6,
  },
  {
    "name": "Aruba",
    "dial_code": "+297",
    "code": "AW",
    "emoji": "🇦🇼",
    "phone_length": 7,
  },
  {
    "name": "Australia",
    "dial_code": "+61",
    "code": "AU",
    "emoji": "🇦🇺",
    "phone_length": 9,
  },
  {
    "name": "Austria",
    "dial_code": "+43",
    "code": "AT",
    "emoji": "🇦🇹",
    "phone_length": 11,
  },
  {
    "name": "Azerbaijan",
    "dial_code": "+994",
    "code": "AZ",
    "emoji": "🇦🇿",
    "phone_length": 9,
  },
  {
    "name": "Bahamas",
    "dial_code": "+1242",
    "code": "BS",
    "emoji": "🇧🇸",
    "phone_length": 10,
  },
  {
    "name": "Bahrain",
    "dial_code": "+973",
    "code": "BH",
    "emoji": "🇧🇭",
    "phone_length": 8,
  },
  {
    "name": "Bangladesh",
    "dial_code": "+880",
    "code": "BD",
    "emoji": "🇧🇩",
    "phone_length": 10,
  },
  {
    "name": "Barbados",
    "dial_code": "+1246",
    "code": "BB",
    "emoji": "🇧🇧",
    "phone_length": 10,
  },
  {
    "name": "Belarus",
    "dial_code": "+375",
    "code": "BY",
    "emoji": "🇧🇾",
    "phone_length": 9,
  },
  {
    "name": "Belgium",
    "dial_code": "+32",
    "code": "BE",
    "emoji": "🇧🇪",
    "phone_length": 9,
  },
  {
    "name": "Belize",
    "dial_code": "+501",
    "code": "BZ",
    "emoji": "🇧🇿",
    "phone_length": 7,
  },
  {
    "name": "Benin",
    "dial_code": "+229",
    "code": "BJ",
    "emoji": "🇧🇯",
    "phone_length": 8,
  },
  {
    "name": "Bermuda",
    "dial_code": "+1441",
    "code": "BM",
    "emoji": "🇧🇲",
    "phone_length": 10,
  },
  {
    "name": "Bhutan",
    "dial_code": "+975",
    "code": "BT",
    "emoji": "🇧🇹",
    "phone_length": 7,
  },
  {
    "name": "Bolivia",
    "dial_code": "+591",
    "code": "BO",
    "emoji": "🇧🇴",
    "phone_length": 9,
  },
  {
    "name": "Bosnia and Herzegovina",
    "dial_code": "+387",
    "code": "BA",
    "emoji": "🇧🇦",
    "phone_length": 8,
  },
  {
    "name": "Botswana",
    "dial_code": "+267",
    "code": "BW",
    "emoji": "🇧🇼",
    "phone_length": 7,
  },
  {
    "name": "Brazil",
    "dial_code": "+55",
    "code": "BR",
    "emoji": "🇧🇷",
    "phone_length": 11,
  },
  {
    "name": "Brunei",
    "dial_code": "+673",
    "code": "BN",
    "emoji": "🇧🇳",
    "phone_length": 7,
  },
  {
    "name": "Bulgaria",
    "dial_code": "+359",
    "code": "BG",
    "emoji": "🇧🇬",
    "phone_length": 9,
  },
  {
    "name": "Burkina Faso",
    "dial_code": "+226",
    "code": "BF",
    "emoji": "🇧🇫",
    "phone_length": 8,
  },
  {
    "name": "Burundi",
    "dial_code": "+257",
    "code": "BI",
    "emoji": "🇧🇮",
    "phone_length": 8,
  },
  {
    "name": "Cambodia",
    "dial_code": "+855",
    "code": "KH",
    "emoji": "🇰🇭",
    "phone_length": 9,
  },
  {
    "name": "Cameroon",
    "dial_code": "+237",
    "code": "CM",
    "emoji": "🇨🇲",
    "phone_length": 9,
  },
  {
    "name": "Canada",
    "dial_code": "+1",
    "code": "CA",
    "emoji": "🇨🇦",
    "phone_length": 10,
  },
  {
    "name": "Cape Verde",
    "dial_code": "+238",
    "code": "CV",
    "emoji": "🇨🇻",
    "phone_length": 7,
  },
  {
    "name": "Cayman Islands",
    "dial_code": "+345",
    "code": "KY",
    "emoji": "🇰🇾",
    "phone_length": 10,
  },
  {
    "name": "Central African Republic",
    "dial_code": "+236",
    "code": "CF",
    "emoji": "🇨🇫",
    "phone_length": 8,
  },
  {
    "name": "Chad",
    "dial_code": "+235",
    "code": "TD",
    "emoji": "🇹🇩",
    "phone_length": 6,
  },
  {
    "name": "Chile",
    "dial_code": "+56",
    "code": "CL",
    "emoji": "🇨🇱",
    "phone_length": 9,
  },
  {
    "name": "China",
    "dial_code": "+86",
    "code": "CN",
    "emoji": "🇨🇳",
    "phone_length": 11,
  },
  {
    "name": "Colombia",
    "dial_code": "+57",
    "code": "CO",
    "emoji": "🇨🇴",
    "phone_length": 10,
  },
  {
    "name": "Costa Rica",
    "dial_code": "+506",
    "code": "CR",
    "emoji": "🇨🇷",
    "phone_length": 8,
  },
  {
    "name": "Cuba",
    "dial_code": "+53",
    "code": "CU",
    "emoji": "🇨🇺",
    "phone_length": 8,
  },
  {
    "name": "Cyprus",
    "dial_code": "+357",
    "code": "CY",
    "emoji": "🇨🇾",
    "phone_length": 8,
  },
  {
    "name": "Czech Republic",
    "dial_code": "+420",
    "code": "CZ",
    "emoji": "🇨🇿",
    "phone_length": 9,
  },
  {
    "name": "Denmark",
    "dial_code": "+45",
    "code": "DK",
    "emoji": "🇩🇰",
    "phone_length": 8,
  },
  {
    "name": "Dominica",
    "dial_code": "+1767",
    "code": "DM",
    "emoji": "🇩🇲",
    "phone_length": 10,
  },
  {
    "name": "Dominican Republic",
    "dial_code": "+1849",
    "code": "DO",
    "emoji": "🇩🇴",
    "phone_length": 10,
  },
  {
    "name": "Ecuador",
    "dial_code": "+593",
    "code": "EC",
    "emoji": "🇪🇨",
    "phone_length": 9,
  },
  {
    "name": "Egypt",
    "dial_code": "+20",
    "code": "EG",
    "emoji": "🇪🇬",
    "phone_length": 10,
  },
  {
    "name": "Estonia",
    "dial_code": "+372",
    "code": "EE",
    "emoji": "🇪🇪",
    "phone_length": 8,
  },
  {
    "name": "Ethiopia",
    "dial_code": "+251",
    "code": "ET",
    "emoji": "🇪🇹",
    "phone_length": 9,
  },
  {
    "name": "Fiji",
    "dial_code": "+679",
    "code": "FJ",
    "emoji": "🇫🇯",
    "phone_length": 7,
  },
  {
    "name": "Finland",
    "dial_code": "+358",
    "code": "FI",
    "emoji": "🇫🇮",
    "phone_length": 11,
  },
  {
    "name": "France",
    "dial_code": "+33",
    "code": "FR",
    "emoji": "🇫🇷",
    "phone_length": 9,
  },
  {
    "name": "Gabon",
    "dial_code": "+241",
    "code": "GA",
    "emoji": "🇬🇦",
    "phone_length": 7,
  },
  {
    "name": "Gambia",
    "dial_code": "+220",
    "code": "GM",
    "emoji": "🇬🇲",
    "phone_length": 7,
  },
  {
    "name": "Georgia",
    "dial_code": "+995",
    "code": "GE",
    "emoji": "🇬🇪",
    "phone_length": 9,
  },
  {
    "name": "Germany",
    "dial_code": "+49",
    "code": "DE",
    "emoji": "🇩🇪",
    "phone_length": 10,
  },
  {
    "name": "Ghana",
    "dial_code": "+233",
    "code": "GH",
    "emoji": "🇬🇭",
    "phone_length": 9,
  },
  {
    "name": "Greece",
    "dial_code": "+30",
    "code": "GR",
    "emoji": "🇬🇷",
    "phone_length": 10,
  },
  {
    "name": "Greenland",
    "dial_code": "+299",
    "code": "GL",
    "emoji": "🇬🇱",
    "phone_length": 6,
  },
  {
    "name": "Grenada",
    "dial_code": "+1473",
    "code": "GD",
    "emoji": "🇬🇩",
    "phone_length": 10,
  },
  {
    "name": "Guatemala",
    "dial_code": "+502",
    "code": "GT",
    "emoji": "🇬🇹",
    "phone_length": 8,
  },
  {
    "name": "Guinea",
    "dial_code": "+224",
    "code": "GN",
    "emoji": "🇬🇳",
    "phone_length": 9,
  },
  {
    "name": "Guyana",
    "dial_code": "+592",
    "code": "GY",
    "emoji": "🇬🇾",
    "phone_length": 7,
  },
  {
    "name": "Honduras",
    "dial_code": "+504",
    "code": "HN",
    "emoji": "🇭🇳",
    "phone_length": 8,
  },
  {
    "name": "Hungary",
    "dial_code": "+36",
    "code": "HU",
    "emoji": "🇭🇺",
    "phone_length": 9,
  },
  {
    "name": "Iceland",
    "dial_code": "+354",
    "code": "IS",
    "emoji": "🇮🇸",
    "phone_length": 7,
  },
  {
    "name": "Indonesia",
    "dial_code": "+62",
    "code": "ID",
    "emoji": "🇮🇩",
    "phone_length": 9,
  },
  {
    "name": "Iran",
    "dial_code": "+98",
    "code": "IR",
    "emoji": "🇮🇷",
    "phone_length": 10,
  },
  {
    "name": "Iraq",
    "dial_code": "+964",
    "code": "IQ",
    "emoji": "🇮🇶",
    "phone_length": 10,
  },
  {
    "name": "Ireland",
    "dial_code": "+353",
    "code": "IE",
    "emoji": "🇮🇪",
    "phone_length": 9,
  },
  {
    "name": "Israel",
    "dial_code": "+972",
    "code": "IL",
    "emoji": "🇮🇱",
    "phone_length": 9,
  },
  {
    "name": "Italy",
    "dial_code": "+39",
    "code": "IT",
    "emoji": "🇮🇹",
    "phone_length": 10,
  },
  {
    "name": "Jamaica",
    "dial_code": "+1876",
    "code": "JM",
    "emoji": "🇯🇲",
    "phone_length": 10,
  },
  {
    "name": "Japan",
    "dial_code": "+81",
    "code": "JP",
    "emoji": "🇯🇵",
    "phone_length": 10,
  },
  {
    "name": "Jordan",
    "dial_code": "+962",
    "code": "JO",
    "emoji": "🇯🇴",
    "phone_length": 9,
  },
  {
    "name": "Kazakhstan",
    "dial_code": "+7",
    "code": "KZ",
    "emoji": "🇰🇿",
    "phone_length": 10,
  },
  {
    "name": "Kenya",
    "dial_code": "+254",
    "code": "KE",
    "emoji": "🇰🇪",
    "phone_length": 9,
  },
  {
    "name": "Kuwait",
    "dial_code": "+965",
    "code": "KW",
    "emoji": "🇰🇼",
    "phone_length": 7,
  },
  {
    "name": "Latvia",
    "dial_code": "+371",
    "code": "LV",
    "emoji": "🇱🇻",
    "phone_length": 8,
  },
  {
    "name": "Lebanon",
    "dial_code": "+961",
    "code": "LB",
    "emoji": "🇱🇧",
    "phone_length": 8,
  },
  {
    "name": "Lithuania",
    "dial_code": "+370",
    "code": "LT",
    "emoji": "🇱🇹",
    "phone_length": 8,
  },
  {
    "name": "Luxembourg",
    "dial_code": "+352",
    "code": "LU",
    "emoji": "🇱🇺",
    "phone_length": 9,
  },
  {
    "name": "Malaysia",
    "dial_code": "+60",
    "code": "MY",
    "emoji": "🇲🇾",
    "phone_length": 7,
  },
  {
    "name": "Maldives",
    "dial_code": "+960",
    "code": "MV",
    "emoji": "🇲🇻",
    "phone_length": 7,
  },
  {
    "name": "Mexico",
    "dial_code": "+52",
    "code": "MX",
    "emoji": "🇲🇽",
    "phone_length": 10,
  },
  {
    "name": "Morocco",
    "dial_code": "+212",
    "code": "MA",
    "emoji": "🇲🇦",
    "phone_length": 9,
  },
  {
    "name": "Nepal",
    "dial_code": "+977",
    "code": "NP",
    "emoji": "🇳🇵",
    "phone_length": 10,
  },
  {
    "name": "Netherlands",
    "dial_code": "+31",
    "code": "NL",
    "emoji": "🇳🇱",
    "phone_length": 9,
  },
  {
    "name": "New Zealand",
    "dial_code": "+64",
    "code": "NZ",
    "emoji": "🇳🇿",
    "phone_length": 9,
  },
  {
    "name": "Nigeria",
    "dial_code": "+234",
    "code": "NG",
    "emoji": "🇳🇬",
    "phone_length": 10,
  },
  {
    "name": "Norway",
    "dial_code": "+47",
    "code": "NO",
    "emoji": "🇳🇴",
    "phone_length": 8,
  },
  {
    "name": "Oman",
    "dial_code": "+968",
    "code": "OM",
    "emoji": "🇴🇲",
    "phone_length": 8,
  },
  {
    "name": "Pakistan",
    "dial_code": "+92",
    "code": "PK",
    "emoji": "🇵🇰",
    "phone_length": 10,
  },
  {
    "name": "Panama",
    "dial_code": "+507",
    "code": "PA",
    "emoji": "🇵🇦",
    "phone_length": 8,
  },
  {
    "name": "Peru",
    "dial_code": "+51",
    "code": "PE",
    "emoji": "🇵🇪",
    "phone_length": 9,
  },
  {
    "name": "Philippines",
    "dial_code": "+63",
    "code": "PH",
    "emoji": "🇵🇭",
    "phone_length": 10,
  },
  {
    "name": "Poland",
    "dial_code": "+48",
    "code": "PL",
    "emoji": "🇵🇱",
    "phone_length": 9,
  },
  {
    "name": "Portugal",
    "dial_code": "+351",
    "code": "PT",
    "emoji": "🇵🇹",
    "phone_length": 9,
  },
  {
    "name": "Qatar",
    "dial_code": "+974",
    "code": "QA",
    "emoji": "🇶🇦",
    "phone_length": 8,
  },
  {
    "name": "Romania",
    "dial_code": "+40",
    "code": "RO",
    "emoji": "🇷🇴",
    "phone_length": 10,
  },
  {
    "name": "Russia",
    "dial_code": "+7",
    "code": "RU",
    "emoji": "🇷🇺",
    "phone_length": 10,
  },
  {
    "name": "Saudi Arabia",
    "dial_code": "+966",
    "code": "SA",
    "emoji": "🇸🇦",
    "phone_length": 9,
  },
  {
    "name": "South Africa",
    "dial_code": "+27",
    "code": "ZA",
    "emoji": "🇿🇦",
    "phone_length": 9,
  },
  {
    "name": "Spain",
    "dial_code": "+34",
    "code": "ES",
    "emoji": "🇪🇸",
    "phone_length": 9,
  },
  {
    "name": "Sri Lanka",
    "dial_code": "+94",
    "code": "LK",
    "emoji": "🇱🇰",
    "phone_length": 7,
  },
  {
    "name": "Sweden",
    "dial_code": "+46",
    "code": "SE",
    "emoji": "🇸🇪",
    "phone_length": 7,
  },
  {
    "name": "Switzerland",
    "dial_code": "+41",
    "code": "CH",
    "emoji": "🇨🇭",
    "phone_length": 9,
  },
  {
    "name": "Thailand",
    "dial_code": "+66",
    "code": "TH",
    "emoji": "🇹🇭",
    "phone_length": 9,
  },
  {
    "name": "Tunisia",
    "dial_code": "+216",
    "code": "TN",
    "emoji": "🇹🇳",
    "phone_length": 8,
  },
  {
    "name": "Turkey",
    "dial_code": "+90",
    "code": "TR",
    "emoji": "🇹🇷",
    "phone_length": 11,
  },
  {
    "name": "United Kingdom",
    "dial_code": "+44",
    "code": "GB",
    "emoji": "🇬🇧",
    "phone_length": 10,
  },
  {
    "name": "United States",
    "dial_code": "+1",
    "code": "US",
    "emoji": "🇺🇸",
    "phone_length": 10,
  },
  {
    "name": "Vietnam",
    "dial_code": "+84",
    "code": "VN",
    "emoji": "🇻🇳",
    "phone_length": 9,
  },
  {
    "name": "Uganda",
    "dial_code": "+256",
    "code": "UG",
    "emoji": "🇺🇬",
    "phone_length": 7,
  },
  {
    "name": "Wallis and Futuna",
    "dial_code": "+681",
    "code": "WF",
    "emoji": "🇼🇫",
    "phone_length": 6,
  },
  {
    "name": "Zambia",
    "dial_code": "+260",
    "code": "ZM",
    "emoji": "🇿🇲",
    "phone_length": 9,
  },
  {
    "name": "Zimbabwe",
    "dial_code": "+263",
    "code": "ZW",
    "emoji": "🇿🇼",
    "phone_length": 9,
  }
];
